/**
 * Databricks deck — L0 panorama (UC Metric Views + Agent Metadata + Genie).
 *
 * Black-box product → every node carries `refs: ['Sx']` pointing into the
 * deck's `sources.ts` catalog (mirroring the WiseCat yaml evaluation evidence).
 * Drillable nodes set `flow: <id>` matching a `DbxFlowDef.id`.
 */
import { ACCENTS, type Accent, type AccentKey, type ArchLayer, type ArchNode } from '../../arch/model/architecture'
import type { Insight, NamedItem } from '../../arch/model/modules'

export { ACCENTS }
export type { Accent, AccentKey, ArchLayer, ArchNode, Insight, NamedItem }

export const DBX_LAYERS: ArchLayer[] = [
  {
    id: 'agent-surface',
    title: 'Agent / Query Surface',
    subtitle: 'Genie Space 是 Databricks 的 NL2SQL 入口；Conversation API 把它暴露成可程序化调用',
    icon: 'i-lucide-message-square',
    accent: 'slate',
    cols: 3,
    nodes: [
      {
        id: 'genie-space',
        label: 'Genie Space',
        sublabel: 'NL → SQL · 选定 metric view / table 子集 · 多轮对话',
        icon: 'i-lucide-sparkles',
        accent: 'slate',
        flow: 'genie',
        span: 1,
        refs: ['S7', 'S9', 'S10'],
      },
      {
        id: 'genie-api',
        label: 'Conversation API',
        sublabel: '/api/2.0/genie/spaces · message/result 程序化调用',
        icon: 'i-lucide-radio',
        accent: 'slate',
        span: 1,
        refs: ['S13'],
      },
      {
        id: 'apps-bi',
        label: 'Apps · BI · Notebook',
        sublabel: 'Databricks Apps · Dashboards · 第三方 BI 经 ODBC/JDBC 消费 metric view',
        icon: 'i-lucide-layout-dashboard',
        accent: 'slate',
        span: 1,
        refs: ['S2'],
      },
    ],
  },
  {
    id: 'semantics',
    title: 'Business Semantics',
    subtitle: '语义层：Metric View（关系+指标模型）+ Agent Metadata（富上下文）',
    icon: 'i-lucide-box',
    accent: 'amber',
    cols: 3,
    nodes: [
      {
        id: 'metric-view',
        label: 'Metric View',
        sublabel: 'YAML: source · joins · dimensions · measures · filter',
        icon: 'i-lucide-shapes',
        accent: 'amber',
        flow: 'metric-view',
        span: 1,
        refs: ['S2', 'S4', 'S5'],
      },
      {
        id: 'agent-metadata',
        label: 'Agent Metadata',
        sublabel: 'synonyms · display_name · format · description',
        icon: 'i-lucide-tags',
        accent: 'amber',
        flow: 'agent-metadata',
        span: 1,
        refs: ['S3'],
      },
      {
        id: 'genie-curate',
        label: 'Genie Curation',
        sublabel: 'example SQL · text instruction · trusted assets · benchmark',
        icon: 'i-lucide-list-checks',
        accent: 'amber',
        flow: 'genie',
        span: 1,
        refs: ['S7', 'S8'],
      },
    ],
  },
  {
    id: 'catalog',
    title: 'Unity Catalog',
    subtitle: 'metric view 是 UC 原生对象 · 三段式命名 · Lakehouse Federation 跨源',
    icon: 'i-lucide-database',
    accent: 'indigo',
    cols: 3,
    nodes: [
      {
        id: 'uc-objects',
        label: 'UC Objects',
        sublabel: 'catalog.schema.{table | view | metric_view} · DDL/GRANT 治理',
        icon: 'i-lucide-folder-tree',
        accent: 'indigo',
        flow: 'uc-federation',
        span: 1,
        refs: ['S1', 'S2', 'S12'],
      },
      {
        id: 'lakehouse-fed',
        label: 'Lakehouse Federation',
        sublabel: 'foreign tables → 跨外部源（PG/MySQL/Snowflake/BQ…）查询',
        icon: 'i-lucide-network',
        accent: 'indigo',
        flow: 'uc-federation',
        span: 1,
        refs: ['S5', 'S11'],
      },
      {
        id: 'system-tables',
        label: 'System Tables',
        sublabel: 'system.* · 审计 / 计量 · metric view 的合法 source',
        icon: 'i-lucide-archive',
        accent: 'indigo',
        span: 1,
        refs: ['S5'],
      },
    ],
  },
  {
    id: 'governance',
    title: 'Governance & Policy',
    subtitle: '策略不在 view 上设、在底表设；查询时按用户身份强制传播',
    icon: 'i-lucide-shield-check',
    accent: 'emerald',
    cols: 3,
    nodes: [
      {
        id: 'policy-runtime',
        label: 'Row Filter / Column Mask',
        sublabel: '设在底表 · 查 metric view 时按当前用户身份生效',
        icon: 'i-lucide-shield',
        accent: 'emerald',
        flow: 'policy-runtime',
        span: 1,
        refs: ['S6'],
      },
      {
        id: 'object-acl',
        label: 'Object ACLs',
        sublabel: 'metric view / table / catalog GRANT · 角色级访问',
        icon: 'i-lucide-key-round',
        accent: 'emerald',
        flow: 'policy-runtime',
        span: 1,
        refs: ['S2', 'S12'],
      },
      {
        id: 'audit',
        label: 'Audit & Lineage',
        sublabel: 'system.access.audit · UC lineage · monitoring',
        icon: 'i-lucide-scroll-text',
        accent: 'emerald',
        span: 1,
        refs: ['S12'],
      },
    ],
  },
  {
    id: 'runtime',
    title: 'Query Runtime',
    subtitle: 'SQL Warehouse 执行 SQL · MV 物化与自动重写影响 SQL 形状',
    icon: 'i-lucide-cpu',
    accent: 'violet',
    cols: 3,
    nodes: [
      {
        id: 'sql-warehouse',
        label: 'SQL Warehouse',
        sublabel: 'Genie 在当前 session / 用户身份下实际执行只读 SQL',
        icon: 'i-lucide-server',
        accent: 'violet',
        span: 1,
        refs: ['S7', 'S10'],
      },
      {
        id: 'mv-materialize',
        label: 'Metric View Materialization',
        sublabel: '增量刷新 + 自动查询重写 · 影响最终 SQL 形状',
        icon: 'i-lucide-snowflake',
        accent: 'violet',
        flow: 'mv-materialize',
        span: 1,
        refs: ['S2', 'S14'],
      },
      {
        id: 'photon',
        label: 'Photon Engine',
        sublabel: '向量化执行引擎 · 按建模 join path 与 cardinality 提示重写',
        icon: 'i-lucide-bolt',
        accent: 'violet',
        span: 1,
        refs: ['S4'],
      },
    ],
  },
]
