package grounding

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"sync/atomic"
	"time"

	"github.com/tmc/langchaingo/llms"
	lctools "github.com/tmc/langchaingo/tools"

	"lucid/internal/adapter"
	"lucid/internal/logger"
	"lucid/internal/react"
	reacttools "lucid/internal/react/tools"
)

// SchemaInfo represents full table schema for linking agent input
type SchemaInfo struct {
	TableName   string       `json:"table_name"`
	Description string       `json:"description,omitempty"`
	RowCount    int64        `json:"row_count,omitempty"`
	Columns     []ColumnInfo `json:"columns"`
	ForeignKeys []FKInfo     `json:"foreign_keys,omitempty"`
}

// ColumnInfo represents column details for linking agent
type ColumnInfo struct {
	Name         string `json:"name"`
	Type         string `json:"type"`
	Description  string `json:"description,omitempty"`
	IsPrimaryKey bool   `json:"is_primary_key,omitempty"`
	IsNullable   bool   `json:"is_nullable,omitempty"`
	SampleValues string `json:"sample_values,omitempty"`
	Synonyms     string `json:"synonyms,omitempty"`
}

// FKInfo represents a foreign key relationship
type FKInfo struct {
	Column           string `json:"column"`
	ReferencedTable  string `json:"referenced_table"`
	ReferencedColumn string `json:"referenced_column"`
}

// LinkingRequest represents a request to the linking agent
type LinkingRequest struct {
	Query   string
	Schemas []SchemaInfo
	// Optional: signals from vector retrieval (large scale mode)
	VectorSignals []*RetrievalSignal
	// Compact mode: only output name+type+PK/FK in prompt (skip RC details).
	// Used in SmallScale where table count is small and RC is not needed for selection.
	Compact bool
}

// LinkingResult represents the linking agent's output
type LinkingResult struct {
	SelectedTables   []SelectedTable
	Reasoning        string
	Duration         time.Duration // T0 → T2 (total wall-clock)
	RetrievalLatency time.Duration // T0 → T1 (vector retrieval; 0 for SmallScale)
	ReasoningLatency time.Duration // T1.1 → T2 (LLM reasoning after schema delivered)
}

// SelectedTable represents a table selected by the linking agent
type SelectedTable struct {
	Name            string           `json:"name"`
	Reason          string           `json:"reason"`
	Confidence      float32          `json:"confidence"`
	Hint            string           `json:"hint,omitempty"` // Query-specific usage hint generated by LLM
	RelevantColumns []RelevantColumn `json:"relevant_columns,omitempty"`
}

// RelevantColumn represents a column identified as relevant by the linking agent.
// This replaces the standalone field-alignment LLM call with zero extra cost.
type RelevantColumn struct {
	Name   string `json:"name"`
	Reason string `json:"reason"`
	Hint   string `json:"hint,omitempty"` // Query-specific usage hint (e.g. "ORDER BY this DESC for '最高'")
}

// LinkingAgent performs LLM-based schema linking with full schema context
type LinkingAgent struct {
	llm    llms.Model
	config LinkingAgentConfig
}

// NewLinkingAgent creates a new linking agent
func NewLinkingAgent(llm llms.Model, config LinkingAgentConfig) *LinkingAgent {
	return &LinkingAgent{
		llm:    llm,
		config: config,
	}
}

// LinkAsync performs schema linking concurrently with schema retrieval.
// The LLM starts at T0 with system prompt + user query; schema data arrives
// later via schemaSlot (written by the caller when vector retrieval completes).
//
// Timeline:
//   T0    — Agent starts, system prompt injected
//   T0.1  — Caller starts vector retrieval concurrently
//   T1    — Retrieval completes, caller writes schema to schemaSlot
//   T1.1  — Agent's get_candidate_schema tool returns non-empty → reasoning starts
//   T2    — Agent outputs Final Answer
//
// Latency metrics:
//   retrieval_latency = T0 → T1 (measured by caller, passed via retrievalDone channel)
//   reasoning_latency = T1.1 → T2 (measured internally via schemaTool.FirstDataTime)
//
// Parameters:
//   - linkingMode: "one-shot" (get_schema → immediate Final Answer) or "react" (get_schema → explore → Final Answer)
//   - schemaSlot: atomic pointer; caller writes schema text when retrieval completes
//   - indexSlot: optional atomic pointer to IndexedPromptResult for resolving [T1]/[C3] labels back to real names
//   - dbAdapter: required for "react" mode (execute_sql tool); nil for "one-shot"
//   - stepCB: optional callback for SSE streaming of ReAct steps
func (a *LinkingAgent) LinkAsync(
	ctx context.Context,
	query string,
	linkingMode string,
	schemaSlot *atomic.Pointer[string],
	indexSlot *atomic.Pointer[IndexedPromptResult],
	dbAdapter adapter.DBAdapter,
	stepCB func(step interface{}, eventType string),
) (*LinkingResult, error) {
	start := time.Now()
	log := logger.With("component", "linking_agent_async")

	log.Info("[LinkAsync] Starting concurrent schema linking",
		"query", query,
		"linking_mode", linkingMode,
	)

	// Build step callback
	var reactStepCallback react.StepCallback
	if stepCB != nil {
		reactStepCallback = func(step react.Step, eventType string) {
			stepCB(step, eventType)
		}
	}

	// Tools: always get_candidate_schema; add execute_sql only for react mode
	schemaTool := reacttools.NewGetCandidateSchema(schemaSlot)
	toolSet := []lctools.Tool{schemaTool}

	var systemPrompt string
	var maxIter, actualMax int

	switch linkingMode {
	case "react":
		// React mode: can explore via execute_sql after getting schema
		if dbAdapter != nil {
			sqlTool := reacttools.NewExecuteSQL(dbAdapter)
			toolSet = append(toolSet, sqlTool)
		}
		systemPrompt = reactLinkingAsyncSystemPrompt
		maxIter = 7
		actualMax = 20
	default: // "one-shot"
		// One-shot mode: must give Final Answer immediately after get_schema
		systemPrompt = oneShotAsyncSystemPrompt
		maxIter = 3  // 1 get_schema + 1 Final Answer + 1 余量
		actualMax = 8
	}

	engineConfig := &react.EngineConfig{
		MaxIterations:     maxIter,
		ActualMaxOverride: actualMax,
		SystemPrompt:      systemPrompt,
		Tools:             toolSet,
		StepCallback:      reactStepCallback,
		LogMode:           "simple",
	}

	engine := react.New(a.llm, engineConfig)

	input := fmt.Sprintf("## User Query\n%s\n\nStart by calling get_candidate_schema to retrieve the database schema. If it returns empty, the data is still loading — call it again.", query)

	result, err := engine.Execute(ctx, input)
	if err != nil {
		log.Error("[LinkAsync] ReAct execution failed", "error", err, "duration", time.Since(start))
		return nil, fmt.Errorf("async linking failed (mode=%s): %w", linkingMode, err)
	}

	// Calculate latency metrics
	endTime := time.Now()
	totalDuration := endTime.Sub(start)
	var reasoningLatency time.Duration
	fdt := schemaTool.FirstDataTime()
	if !fdt.IsZero() {
		reasoningLatency = endTime.Sub(fdt)
	}

	log.Info("[LinkAsync] Execution completed",
		"linking_mode", linkingMode,
		"iterations", result.Iterations,
		"schema_polls", schemaTool.CallCount(),
		"total_duration", totalDuration.Round(time.Millisecond),
		"reasoning_latency", reasoningLatency.Round(time.Millisecond),
		"schema_delivered", !fdt.IsZero(),
	)

	// Parse final answer — use index maps if available for resolving [T1]/[C3] labels
	var indexed *IndexedPromptResult
	if indexSlot != nil {
		indexed = indexSlot.Load()
	}
	selected, reasoning, err := a.parseLinkingResponse(result.Output, indexed)
	if err != nil {
		log.Error("[LinkAsync] Failed to parse output", "error", err,
			"output", truncateLinking(result.Output, 300))
		return nil, fmt.Errorf("failed to parse async linking response: %w", err)
	}

	// Filter by confidence
	var filtered []SelectedTable
	for _, t := range selected {
		if t.Confidence >= a.config.ConfidenceThreshold {
			filtered = append(filtered, t)
		}
	}

	selectedNames := make([]string, len(filtered))
	for i, t := range filtered {
		selectedNames[i] = t.Name
	}
	log.Info("[LinkAsync] Schema linking completed",
		"selected_tables", strings.Join(selectedNames, ", "),
		"schema_polls", schemaTool.CallCount(),
		"total_duration", totalDuration.Round(time.Millisecond),
		"reasoning_latency", reasoningLatency.Round(time.Millisecond),
	)

	return &LinkingResult{
		SelectedTables:   filtered,
		Reasoning:        reasoning,
		Duration:         totalDuration,
		ReasoningLatency: reasoningLatency,
	}, nil
}

// oneShotAsyncSystemPrompt is used for one-shot mode in the concurrent architecture.
// The LLM calls get_candidate_schema to obtain the schema, then MUST immediately
// produce Final Answer — no exploration via execute_sql is allowed.
const oneShotAsyncSystemPrompt = `You are an expert database schema analyst performing Schema Linking.

Your task: Given a natural language query, retrieve the database schema and identify which tables and columns are needed to answer the query.

## Workflow
1. Call get_candidate_schema to retrieve the database schema. If it returns empty, the data is still loading — call it again.
2. Once you have the schema, analyze it and IMMEDIATELY produce your Final Answer. Do NOT call any other tools.

The schema uses index labels: [T1], [T2] for tables; [C1], [C2] for columns. Use these labels in your Final Answer.

## Output Format

When retrieving schema:
Thought: I need to retrieve the database schema first.
Action: get_candidate_schema
Action Input: retrieve

When ready (MUST be your very next response after receiving schema):
Thought: [your analysis]
Final Answer: [JSON object]

The Final Answer MUST be a valid JSON object:
{
  "tables": ["T1", "T3"],
  "columns": ["C2", "C5", "C8"],
  "hints": {
    "C5": "COUNT + GROUP BY for most-played",
    "C8": "WHERE this = 'value' based on sample data"
  },
  "reasoning": "Brief explanation"
}

Note: If the schema does not contain index labels, use real table/column names in the same format.

Rules:
- "tables": list of table index labels. Include ALL tables needed for JOINs.
- "columns": list of column index labels. Include relevant columns only.
- "hints": only for key columns (WHERE/JOIN/ORDER BY/GROUP BY targets). Omit obvious ones.
- "reasoning": one or two sentences.
- Be thorough: missing a table is worse than including an extra one.
- IMPORTANT: You MUST give Final Answer immediately after receiving the schema. Do NOT call execute_sql or any other tool.`

// reactLinkingAsyncSystemPrompt is used for react mode in the concurrent architecture.
// The LLM calls get_candidate_schema first, then can explore via execute_sql.
const reactLinkingAsyncSystemPrompt = `You are an expert database schema analyst performing ReAct Schema Linking.

Your task: Given a natural language query, retrieve the database schema and identify which tables and columns are needed to answer the query.

The schema uses index labels: [T1], [T2] for tables; [C1], [C2] for columns. Use these labels in your Final Answer.

## Strategy
1. **First**: Call get_candidate_schema to retrieve the database schema. If it returns empty, the schema data is still loading — call it again.
2. Once you have the schema, review it and identify candidate tables
3. When uncertain, use execute_sql to explore the database (sample data, distributions, joins)
4. Select the final set of relevant tables and columns

⚠️ ITERATION LIMIT: Maximum 7 iterations. Be efficient.

## Output Format

When retrieving or exploring, use:
Thought: [your reasoning]
Action: get_candidate_schema OR execute_sql
Action Input: [input]

When ready to give your final answer:
Thought: [summary of findings]
Final Answer: [JSON object]

The Final Answer MUST be a valid JSON object:
{
  "tables": ["T1", "T3"],
  "columns": ["C2", "C5", "C8"],
  "hints": {
    "C5": "COUNT + GROUP BY for most-played",
    "C8": "WHERE this = 'value' based on sample data"
  },
  "reasoning": "Brief explanation"
}

Note: If the schema does not contain index labels, use real table/column names in the same format:
{
  "tables": ["table_name1", "table_name2"],
  "columns": ["col1", "col2"],
  "hints": {"col1": "hint"},
  "reasoning": "..."
}

IMPORTANT:
- Include ALL tables needed for JOINs
- Only include relevant columns, not every column
- Generate hints only for key columns
- Reference actual data values from your exploration in hints when possible
- Be thorough: missing a table is worse than including an extra one`

// indexedColumn stores the mapping from column index label back to table+column name.
type indexedColumn struct {
	TableName  string
	ColumnName string
}

// IndexedPromptResult holds the prompt text plus the index→entity reverse lookup maps,
// so parseLinkingResponse can resolve [T1]/[C3] labels back to real names.
type IndexedPromptResult struct {
	Prompt       string
	TableIndex   map[string]string        // "T1" → "TV_Channel"
	ColumnIndex  map[string]indexedColumn  // "C3" → {TableName, ColumnName}
}

func (a *LinkingAgent) buildLinkingPrompt(req *LinkingRequest) string {
	r := a.buildIndexedLinkingPrompt(req)
	return r.Prompt
}

func (a *LinkingAgent) buildIndexedLinkingPrompt(req *LinkingRequest) IndexedPromptResult {
	var sb strings.Builder
	tableIdx := make(map[string]string)        // "T1" → table name
	colIdx := make(map[string]indexedColumn)    // "C3" → {table, column}

	sb.WriteString(fmt.Sprintf("## User Query\n%s\n\n", req.Query))
	sb.WriteString("## Database Schema\n\n")

	// If we have vector signals, annotate tables with retrieval scores
	signalScores := make(map[string]float32)
	if len(req.VectorSignals) > 0 {
		for _, sig := range req.VectorSignals {
			if sig.SignalType == SignalTypeTable {
				signalScores[sig.EntityName] = sig.Score
			}
		}
	}

	tNum := 1  // table counter
	cNum := 1  // global column counter

	for _, schema := range req.Schemas {
		tLabel := fmt.Sprintf("T%d", tNum)
		tableIdx[tLabel] = schema.TableName

		// Table header with index label + optional retrieval score
		sb.WriteString(fmt.Sprintf("### [%s] `%s`", tLabel, schema.TableName))
		if score, ok := signalScores[schema.TableName]; ok {
			sb.WriteString(fmt.Sprintf(" (vector relevance: %.2f)", score))
		}
		sb.WriteString("\n")

		if !req.Compact && schema.Description != "" {
			sb.WriteString(fmt.Sprintf("Description: %s\n", schema.Description))
		}
		if schema.RowCount > 0 {
			sb.WriteString(fmt.Sprintf("Row count: %d\n", schema.RowCount))
		}

		// Columns — compact mode omits RC details to reduce prompt size
		includeRC := a.config.IncludeRichContext && !req.Compact
		if len(schema.Columns) > 0 && a.config.IncludeColumnDetails {
			sb.WriteString("Columns:\n")
			for _, col := range schema.Columns {
				cLabel := fmt.Sprintf("C%d", cNum)
				colIdx[cLabel] = indexedColumn{TableName: schema.TableName, ColumnName: col.Name}

				sb.WriteString(fmt.Sprintf("  - [%s] `%s` (%s)", cLabel, col.Name, col.Type))
				if col.IsPrimaryKey {
					sb.WriteString(" [PK]")
				}
				if !col.IsNullable {
					sb.WriteString(" [NOT NULL]")
				}
				sb.WriteString("\n")

				if includeRC {
					if col.Description != "" {
						sb.WriteString(fmt.Sprintf("    Description: %s\n", col.Description))
					}
					if col.SampleValues != "" {
						sb.WriteString(fmt.Sprintf("    Sample values: %s\n", col.SampleValues))
					}
					if col.Synonyms != "" {
						sb.WriteString(fmt.Sprintf("    Synonyms: %s\n", col.Synonyms))
					}
				}
				cNum++
			}
		}

		// Foreign keys
		if len(schema.ForeignKeys) > 0 {
			sb.WriteString("Foreign keys:\n")
			for _, fk := range schema.ForeignKeys {
				sb.WriteString(fmt.Sprintf("  - %s → %s.%s\n", fk.Column, fk.ReferencedTable, fk.ReferencedColumn))
			}
		}
		sb.WriteString("\n")
		tNum++
	}

	// If large scale mode with vector signals, add a hint
	if len(req.VectorSignals) > 0 {
		sb.WriteString("---\n")
		sb.WriteString("Note: Tables annotated with 'vector relevance' scores were identified by semantic search as potentially relevant. ")
		sb.WriteString("Use these scores as hints, but make your own judgment based on the full schema.\n")
	}

	sb.WriteString("\nSelect the tables and columns needed to answer the query using their index labels ([T1], [C3], etc.). Be thorough — missing a table is worse than including an extra one.")

	return IndexedPromptResult{
		Prompt:      sb.String(),
		TableIndex:  tableIdx,
		ColumnIndex: colIdx,
	}
}

func truncateLinking(s string, maxLen int) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.TrimSpace(s)
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}

// linkingResponse represents the LLM's linking response — old verbose format (backward compat)
type linkingResponseVerbose struct {
	Tables []struct {
		Name            string  `json:"name"`
		Reason          string  `json:"reason"`
		Confidence      float32 `json:"confidence"`
		Hint            string  `json:"hint"`
		RelevantColumns []struct {
			Name   string `json:"name"`
			Reason string `json:"reason"`
			Hint   string `json:"hint"`
		} `json:"relevant_columns"`
	} `json:"tables"`
	Reasoning string `json:"reasoning"`
}

// linkingResponseIndexed represents the new compact index-based format
type linkingResponseIndexed struct {
	Tables    []string          `json:"tables"`    // ["T1", "T3"]
	Columns   []string          `json:"columns"`   // ["C2", "C5"]
	Hints     map[string]string `json:"hints"`     // {"C5": "COUNT + GROUP BY ..."}
	Reasoning string            `json:"reasoning"`
}

func (a *LinkingAgent) parseLinkingResponse(content string, indexed *IndexedPromptResult) ([]SelectedTable, string, error) {
	// Extract JSON from response
	jsonStr := content
	if idx := strings.Index(content, "```json"); idx != -1 {
		start := idx + 7
		end := strings.Index(content[start:], "```")
		if end != -1 {
			jsonStr = content[start : start+end]
		}
	} else if idx := strings.Index(content, "{"); idx != -1 {
		jsonStr = content[idx:]
		if endIdx := strings.LastIndex(jsonStr, "}"); endIdx != -1 {
			jsonStr = jsonStr[:endIdx+1]
		}
	}

	// Try indexed format first (tables is array of strings)
	var indexedResp linkingResponseIndexed
	if err := json.Unmarshal([]byte(jsonStr), &indexedResp); err == nil && len(indexedResp.Tables) > 0 {
		// Check if first element looks like an index label (starts with "T")
		if strings.HasPrefix(indexedResp.Tables[0], "T") && indexed != nil {
			return a.resolveIndexedResponse(&indexedResp, indexed)
		}
		// Could be table names directly (e.g. ["TV_Channel", "Cartoon"])
		// Check if they exist in the index values
		if indexed != nil {
			// Check if these are real table names rather than index labels
			isRealName := false
			for _, tLabel := range indexedResp.Tables {
				if _, ok := indexed.TableIndex[tLabel]; !ok {
					isRealName = true
					break
				}
			}
			if isRealName {
				return a.resolveNameBasedResponse(&indexedResp, indexed)
			}
			return a.resolveIndexedResponse(&indexedResp, indexed)
		}
		// No index available (ReactLinkAsync) — treat as table names
		return a.resolveNameBasedResponse(&indexedResp, nil)
	}

	// Fall back to verbose format (backward compat for ReAct modes)
	var verboseResp linkingResponseVerbose
	if err := json.Unmarshal([]byte(jsonStr), &verboseResp); err != nil {
		return nil, "", fmt.Errorf("failed to parse JSON: %w", err)
	}

	var tables []SelectedTable
	for _, t := range verboseResp.Tables {
		st := SelectedTable{
			Name:       t.Name,
			Reason:     t.Reason,
			Confidence: t.Confidence,
			Hint:       t.Hint,
		}
		for _, col := range t.RelevantColumns {
			st.RelevantColumns = append(st.RelevantColumns, RelevantColumn{
				Name:   col.Name,
				Reason: col.Reason,
				Hint:   col.Hint,
			})
		}
		tables = append(tables, st)
	}

	return tables, verboseResp.Reasoning, nil
}

// resolveIndexedResponse converts index-label responses (["T1","T3"], ["C2","C5"]) to SelectedTable structs
func (a *LinkingAgent) resolveIndexedResponse(resp *linkingResponseIndexed, indexed *IndexedPromptResult) ([]SelectedTable, string, error) {
	// Group columns by table
	tableColumns := make(map[string][]RelevantColumn) // tableName → columns
	for _, cLabel := range resp.Columns {
		ic, ok := indexed.ColumnIndex[cLabel]
		if !ok {
			continue
		}
		rc := RelevantColumn{
			Name: ic.ColumnName,
		}
		if hint, hasHint := resp.Hints[cLabel]; hasHint {
			rc.Hint = hint
			rc.Reason = hint // Use hint as reason for backward compat
		}
		tableColumns[ic.TableName] = append(tableColumns[ic.TableName], rc)
	}

	var tables []SelectedTable
	for _, tLabel := range resp.Tables {
		tableName, ok := indexed.TableIndex[tLabel]
		if !ok {
			continue
		}
		st := SelectedTable{
			Name:            tableName,
			Reason:          "Selected via index " + tLabel,
			Confidence:      0.9, // Default high confidence for indexed selection
			RelevantColumns: tableColumns[tableName],
		}
		tables = append(tables, st)
	}

	return tables, resp.Reasoning, nil
}

// resolveNameBasedResponse handles cases where LLM outputs real table names instead of index labels
func (a *LinkingAgent) resolveNameBasedResponse(resp *linkingResponseIndexed, indexed *IndexedPromptResult) ([]SelectedTable, string, error) {
	// Build reverse lookup: table name → label
	var nameToLabel map[string]string
	// Build reverse lookup: column name → column index entries
	var colNameToEntries map[string][]indexedColumn

	if indexed != nil {
		nameToLabel = make(map[string]string)
		for label, name := range indexed.TableIndex {
			nameToLabel[name] = label
		}
		colNameToEntries = make(map[string][]indexedColumn)
		for label, ic := range indexed.ColumnIndex {
			_ = label
			colNameToEntries[ic.ColumnName] = append(colNameToEntries[ic.ColumnName], ic)
		}
	}

	// Group columns by table
	tableColumns := make(map[string][]RelevantColumn)
	for _, cRef := range resp.Columns {
		// cRef might be "C5" (index) or "column_name" (real name)
		if indexed != nil {
			if ic, ok := indexed.ColumnIndex[cRef]; ok {
				rc := RelevantColumn{Name: ic.ColumnName}
				if hint, ok := resp.Hints[cRef]; ok {
					rc.Hint = hint
					rc.Reason = hint
				}
				tableColumns[ic.TableName] = append(tableColumns[ic.TableName], rc)
				continue
			}
		}
		// Treat as column name — we don't know which table it belongs to
		rc := RelevantColumn{Name: cRef}
		if hint, ok := resp.Hints[cRef]; ok {
			rc.Hint = hint
			rc.Reason = hint
		}
		// Try to find the table
		if colNameToEntries != nil {
			if entries, ok := colNameToEntries[cRef]; ok && len(entries) > 0 {
				tableColumns[entries[0].TableName] = append(tableColumns[entries[0].TableName], rc)
				continue
			}
		}
		tableColumns["_unknown_"] = append(tableColumns["_unknown_"], rc)
	}

	var tables []SelectedTable
	for _, tRef := range resp.Tables {
		tableName := tRef
		st := SelectedTable{
			Name:            tableName,
			Reason:          "Selected by linking agent",
			Confidence:      0.9,
			RelevantColumns: tableColumns[tableName],
		}
		tables = append(tables, st)
	}

	return tables, resp.Reasoning, nil
}
